### ISSUE TITLE
Win by Diagonal is not recognized as a win.

### ISSUE THREAD

**Issue by NikolaBV** [Gennifire/ticTacToe#3]
When you win by doing 3 in a row diagonally the game doesn't recognize it as a win.
![Screenshot_1](https://user-images.githubusercontent.com/54500207/200081818-80514ec8-de82-430a-9cf8-ac31effe153f.jpg)
![Uploading Screenshot_2.jpg…]()

**Comment by Gennifire** [comment]
O Diagonal Win
![OdiagonalWin](https://user-images.githubusercontent.com/72698786/205626797-1187b035-c121-4e16-80d5-a4caf3d677b3.png)

X Diagonal Win
![diagonalWin](https://user-images.githubusercontent.com/72698786/205626809-898722d0-b848-4469-bb08-eed34c3936f8.png)
